//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCudec1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public int idEnvio { get; set; }
        public string CodigoPostal { get; set; }
        public string Estado { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> idCompra { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
