//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCudec1
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string Sexo { get; set; }
        public string User_Name { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public byte[] Foto_de_perfil { get; set; }
        public int Compra_idCompra { get; set; }
        public int Tipo_de_usuario_idTipo_de_usuario { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Tipo_de_usuario Tipo_de_usuario { get; set; }
    }
}
